language: java
dist: trusty
jdk: openjdk8
        - 
before_install:
        - chmod +x mvnw
install:
        - ./mvnw test -B org.jacoco:jacoco-maven-plugin:report org.eluder.coveralls:coveralls-maven-plugin:report
